services:
  go-web-app:
    container_name: collectables-api
    network_mode: "host"
    restart: always
    build: .
    working_dir: /go-server
    expose:
      - "3000"
    ports:
      - "3000:3000"
