name: collections-api
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v1
      - name: Deploy para host
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzv0 --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/.git/, /.github/"
          SCRIPT_BEFORE: |
            mv /home/collections-api/api/.env /home/collections-api/.env
          SCRIPT_AFTER: |
            mv /home/collections-api/.env /home/collections-api/api/.env
            cd /home/collections-api/api
            chmod +x ./deploy.sh
            ./deploy.sh
